#!/bin/zsh
#
# This lets you quickly jump into a presentation directory.
#
# Type:
#
#   p <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_p`. Typically I'm using it like:
#
#    p gra<tab>/p<tab>
#
# ...to quickly jump into GraphQL/Primer, for example.

cd "$PRESENTATIONS/$1"
